### ISSUE TITLE
doc clustering page for v5 refer to restheart v4

### ISSUE THREAD

**Issue by ujibang** [SoftInstigate/restheart-website#29]
the page https://restheart.org/docs/clustering/ contains references to RH v4.

**Comment by ujibang** [comment]
RH5 can be deployed the same way than RH4. 

The configuration file has a proxy section: a first instance (with security services enabled and mongo service disabled) can proxy requests to a second instance (with security disabled and mongo service enabled).

**Comment by mkjsix** [comment]
Removed old references to v4 and fixed typos. However we need to add something about the new token manager, as I can't find any explanation in the docs (at least related to clustering)
